### ISSUE TITLE
HOW TO ACTIVATE TESTNET ON BITMEX ?

### ISSUE THREAD

**Issue by azulflowing** [gruelbox/orko#348]
can anyone help please activating the testnet for bitmex ?

**Comment by badgerwithagun** [comment]
How do you have Orko deployed?

**Comment by azulflowing** [comment]
both local and heroku and **thank you** for replying

**Comment by badgerwithagun** [comment]
OK, Bitmex is not fully working yet, so bear that in mind, but locally you should be able to use the testnet by setting `sandbox: true` in the config:
```
  bitmex:
    apiKey: YOUR-KEY
    secretKey: YOUR_SECRET
    loadRemoteData: true
    sandbox: true
```

There's no mapping for this on Heroku at the moment.  Please say if the above works and I can add it pretty easily to Heroku too.
